include: "workflow/rules/dorado.smk"
include: "workflow/rules/get_transcriptome.smk"
include: "workflow/rules/minimap2_alignment.smk"
include: "workflow/rules/seq2mv.smk"
include: "workflow/rules/sort.smk"
include: "workflow/rules/squigualiser.smk"
include: "workflow/rules/slice_bam.smk"